# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a415a379851083eee0b3c55d8d27ae8d492da3393aafb8f6141763d309507736a86f20b0a830463575791758f32ddd7c39a7a62ea9ba2af3fd5db93448a981c

test:
  secret_key_base: 4a9f19ede7823767291abbe1d9efd456ef6fb9adcc6321ed693790de3cf3759f1a1ced339205cf3abb3349edfb3aff82ad09c385f49db83fe3399dea36bcef08

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
